### ISSUE TITLE
The command 'ble dis' doesn't work

### ISSUE THREAD

**Issue by Burzo** [wildlifeai/wildlife-watcher-mobile-app#19]
It seems that the command `ble dis` doesn't work, nothing happens.

![image](https://github.com/wildlifeai/wildlife-watcher-mobile-app/assets/15817804/a0943f2a-2b11-48e8-b56d-da1cd588f796)

**Comment by acutetech** [comment]
Looks like there are errors and omissions with some of the commands on the WW120_D00 sent to Miha. These include the 'dis' command being missing. (You can press the Disconnect elsewhere on the nRF Toolbox application).

I have implemented and tested this on the REWILD 2 application, for the WW130_A00, which I will get to Miha ASAP.

**Comment by Burzo** [comment]
Works on the new board.
