### ISSUE TITLE
Set up framework/libraries for mobile app

### ISSUE THREAD

**Issue by victor-wildlife** [wildlifeai/wildlife-watcher-mobile-app#55]
Framework/library to connect to API

- [x] Update readme documentation
- [x] Add documentation on how to release
- [x] Add RTK Query

**Comment by victor-wildlife** [comment]
@Burzo is there any task still outstanding from the proposed checklist?

**Comment by Burzo** [comment]
There are still 2 issues left yeh, I updated them. One is relatively easy, the other one is heavily dependent on the backend to work.

**Comment by Burzo** [comment]
This was now done 👍
